<?php
include_once POS_ROOT . '/default/settings.php';
include_once POS_ROOT . '/helper/variables.php';
include_once POS_ROOT . '/helper/Helper.php';
include_once POS_ROOT . '/dataAccessLayer/Connection.php';
include_once POS_ROOT . '/dataAccessLayer/DataAccessManager.php';
include_once POS_ROOT . '/businessLayer/UserBusinessLayer.php';
include_once POS_ROOT . '/businessLayer/PermissionBusinessLayer.php';
include_once POS_ROOT . '/helper/Menu.php';
?>